config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  get "/users", to: "users#index", as: "users"
  get "/signup", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"

  get "/login", to: "sessions#new", as: "new_session"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  # get "/scores/new", to: "scores#new", as: "new_score"
  get "/scores", to: "scores#index", as: "top_scores"
  post "/scores", to: "scores#create"

end

app/models/score.rb
class Score < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def index
    @top_scores = Score.all.limit(20).order('top_score DESC')
    @score_show = false;
  end
  def new
    @score = Score.new

  end
  def create
    # @user = User.find_by_id(params[:id])
    score_params = params.permit(:top_score)
    @score = Score.new(score_params)
    @score.save
    render :nothing => true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # def new
  #   @user = User.new
  # end

  # def create
  #   user_params = params.require(:user).permit(:username, :password)
  #   @user = User.confirm(user_params)
  #   if @user
  #     login(@user)
  #     redirect_to @user
  #   else
  #     redirect_to new_session_path
  #   end
  # end

  # def destroy
  #   logout
  #   redirect_to root_path
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 # before_action :logged_in?, except: [:new, :create]

  def index
    @score_show = true;
  end

  def show
    # @user = User.find_by_id(params[:id])
    # # @scores = @user.scores.limit(10).order('user_score DESC')
    # @score_show = false
  end

  def new
    # @user = User.new
    # @score_show = false
  end
  def create
    # @user = User.create(user_params)
    # login(@user)
    #
    # redirect_to @user
  end

  # private
  #
  # def user_params
  #   params.require(:user).permit(:username, :password)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # def login(user)
  #   session[:user_id] = user.id
  #   @current_user = user
  # end
  #
  # def current_user
  #   @current_user ||= User.find_by_id(session[:user_id])
  # end
  #
  # def logged_in?
  #   if current_user == nil
  #     redirect_to new_session_path
  #   end
  # end
  #
  # def logout
  #   @current_user = session[:user_id] = nil
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Objekts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>
  <nav class="mynav">
    <div class="menu">
        <!-- <a><%= link_to "Top Scores", scores_path, { class: "top-scores-nav" } %></a> -->
        <div class="<%= @score_show ? 'score' : 'hidden-score' %>"><p id="score">0000</p></div>
    </div>
  </nav>
  <div class="flash">
    <% flash.each do |name, msg| %>
      <p>
        <small class="alert alert-info"> <%= name.capitalize %>: <%= msg %> </small>
      </p>
    <% end %>
  </div>
<%= yield %>

<%= Gon::Base.render_data %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'welcome'%>
<%= csrf_meta_tags %>

</body>
</html>

app/views/scores/index.html.erb
<div class="top-scores">
  <h2> Top Scores </h2> <br>
  <hr class="scores-hr">
  <% @top_scores.each do |s| %>
    <div class="top-scores-name">
      <%= s.username %>
    </div>
    <br>
    <div class="top-scores-score">
      <%= s.top_score %>
    </div>
    <div class="top-scores-date">
      <%= s.created_at.strftime("%m/%d/%Y") %>
    </div>
      <hr class="scores-hr">
  <% end %>
</div>

app/views/users/index.html.erb
<%= image_tag( 'herman.png', :class => "hiddenImage" ) %>
<%= image_tag( 'phil.png', :class => "hiddenImage" ) %>
<%= image_tag( 'marcelo.png', :class => "hiddenImage" ) %>
<div id="space"></div>

app/views/users/new.html.erb
  <div class="welcome-sphere" id="welcome-sphere">

  </div>